services:
  - type: web
    name: timisoara-rent-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -u server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TELEGRAM_BOT_TOKEN
        value: 8903183307:AAGNYo9gBNTVSTV9AferFGkDK0hLP4ykxIc

